#!/usr/bin/env python3
"""
Merge per-topic bibliography and glossary fragments into the root TSVs.

    python tools/merge_refs.py            # write references.tsv and glossary.tsv
    python tools/merge_refs.py --check    # report problems, write nothing

Every folder under content/ may carry a `refs.tsv` (slug, grade, title, url,
note) and a `terms.tsv` (slug, label, definition). Research agents write one
fragment per topic with a topic-specific slug prefix; this script concatenates
them deterministically (sorted by path, then by slug) and fails on a slug that
appears twice with different content. A slug repeated with identical content is
kept once.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"

ALLOWED_GRADES = {
    "primary", "peer-reviewed", "preprint", "company",
    "survey", "trade", "vendor", "unsourced",
}

IMAGES_HEADER = """# path\tkind\tlicence\tsource\tnote
# path is relative to content/. kind: own | third-party.
# An "own" figure names its generating script in tools/figures/ as its source.
# A third-party image names its licence and the page it came from.
# GENERATED by tools/merge_refs.py from content/**/images.tsv.
"""

REFS_HEADER = """# slug\tgrade\ttitle\turl\tnote
# Grades: primary | peer-reviewed | preprint | company | survey | trade | vendor | unsourced
# GENERATED by tools/merge_refs.py from content/**/refs.tsv. Edit the fragments, not this file.
"""

TERMS_HEADER = """# slug\tlabel\tdefinition
# GENERATED by tools/merge_refs.py from content/**/terms.tsv. Edit the fragments, not this file.
"""


def read_rows(path: Path, nfields: int, errors: list[str]) -> list[tuple[str, list[str]]]:
    rows = []
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip("\r\n")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = [p.strip() for p in line.split("\t")]
        if len(parts) < nfields or not all(parts[:nfields]):
            errors.append(f"{path.relative_to(ROOT)} line {lineno}: expected {nfields} non-empty fields, got {len(parts)}")
            continue
        rows.append((parts[0], parts))
    return rows


def merge(kind: str, nfields: int, errors: list[str]) -> list[list[str]]:
    seen: dict[str, tuple[list[str], Path]] = {}
    out: list[list[str]] = []
    for frag in sorted(CONTENT.rglob(kind)):
        for slug, parts in read_rows(frag, nfields, errors):
            if kind == "refs.tsv" and parts[1].lower() not in ALLOWED_GRADES:
                errors.append(f"{frag.relative_to(ROOT)}: unknown grade '{parts[1]}' for '{slug}'")
            if slug in seen:
                prev, where = seen[slug]
                if prev != parts:
                    msg = f"{frag.relative_to(ROOT)}: slug '{slug}' already defined differently in {where.relative_to(ROOT)}"
                    if kind == "terms.tsv":
                        # Two topics defining the same term in different words is
                        # expected; the first definition (by path order) wins.
                        print(f"note: {msg}; keeping the first", file=sys.stderr)
                    else:
                        errors.append(msg)
                continue
            seen[slug] = (parts, frag)
            out.append(parts)
    out.sort(key=lambda p: p[0])
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    errors: list[str] = []
    refs = merge("refs.tsv", 4, errors)
    terms = merge("terms.tsv", 3, errors)
    images = merge("images.tsv", 4, errors)
    for e in errors:
        print(f"ERROR: {e}", file=sys.stderr)
    print(f"{len(refs)} references, {len(terms)} glossary terms, "
          f"{len(images)} images from fragments")
    if errors:
        return 1
    if args.check:
        return 0
    (ROOT / "references.tsv").write_text(
        REFS_HEADER + "".join("\t".join(r[:5]) + "\n" for r in refs), encoding="utf-8", newline="\n")
    (ROOT / "glossary.tsv").write_text(
        TERMS_HEADER + "".join("\t".join(t[:3]) + "\n" for t in terms), encoding="utf-8", newline="\n")
    (ROOT / "images.tsv").write_text(
        IMAGES_HEADER + "".join("\t".join(i[:5]) + "\n" for i in images), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
